name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin' # Hier geben wir die Distribution an

    - name: Compile Java
      run: javac HelloWorld.java

    - name: Run Java Program
      run: java HelloWorld
